name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [20.x]
    outputs:
      host_name: ${{ steps.import-env.outputs.host_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: get gh token from my-gh-app
        id: gh-app-auth
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          repositories: common-merlin-ui-kit,digital-ticketing-portal-infra

      - run: |
          git config --global url."https://oauth2:${{ steps.gh-app-auth.outputs.token }}@github.com".insteadOf ssh://git@github.com
          npm ci

      - name: Run ESLint
        run: npm run lint

      - run: npm run build

      - name: Package Files
        run: cd dist && zip -r "../ticketing-pwa-${{ github.event.pull_request.number }}.zip" *

      - name: Make pwa release
        run: cp "ticketing-pwa-${{ github.event.pull_request.number }}.zip" ticketing-pwa.zip

      - name: Upload Artifact for Pull Request
        if: github.event_name == 'pull_request'
        id: pull_request_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ticketing-pwa
          path: "ticketing-pwa.zip"
          retention-days: 1
          overwrite: true

      - name: Generate release tag
        if: github.event_name == 'push'
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v5.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          tag_template: "yyyy.mm.dd.i"

      - name: Update Latest Artifact
        if: github.event_name == 'push'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          artifacts: "ticketing-pwa.zip"

      - name: Trigger infra pipeline to deploy latest release
        if: github.event_name == 'push'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.gh-app-auth.outputs.token }}
          repository: MerlinEntertainments/digital-ticketing-portal-infra
          event-type: deployment

      - name: Dispatch an action and get the run ID
        if: github.event_name == 'pull_request'
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          ref: refs/heads/main
          token: ${{ steps.gh-app-auth.outputs.token }}
          repo: digital-ticketing-portal-infra
          owner: MerlinEntertainments
          workflow: on-pwa-repo-pull-request.yml
          workflow_inputs: '{"artifactId": "${{ steps.pull_request_artifact.outputs.artifact-id }}", "pr_number": "${{ github.event.pull_request.number }}"}'

      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        if: github.event_name == 'pull_request'  
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ steps.gh-app-auth.outputs.token }}
          repo: digital-ticketing-portal-infra
          owner: MerlinEntertainments
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 600
          poll_interval_ms: 5000

      - name: Download infra output artifact
        uses: actions/download-artifact@v4
        with:
          name: env
          github-token: ${{ steps.gh-app-auth.outputs.token }}
          repository: MerlinEntertainments/digital-ticketing-portal-infra
          run-id: ${{ steps.return_dispatch.outputs.run_id }}

      - name: Import environment variables from the file
        id: import-env
        shell: bash
        run: cat env >> $GITHUB_OUTPUT

  Integration-Tests-SIT:
    needs: [build]
    if: github.event_name == 'push'
    uses: ./.github/workflows/cypress-integration.yml
    with:
      HOSTNAME: "https://dfe-ticketing-portal-sit-euw-000-gug5b8bgdyhwhhev.a01.azurefd.net"
    secrets: inherit
    permissions:
      contents: write

  Integration-Tests-DEV:
    needs: [build]
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/cypress-integration.yml
    with:
      HOSTNAME: "https://${{ needs.build.outputs.host_name }}"
    secrets: inherit
    permissions:
      contents: write
