name: Lighthouse CI

on:
  push:
    branches:
      - lighthouse
  pull_request:
    branches:
      - lighthouse

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: npm install
        run: npm install
        
      - name: Install xvfb
        run: sudo apt-get install -y xvfb
        
      - name: Start App
        run: |
          nohup npm run dev &
          sleep 5 # Wait for a while to ensure the app starts
          curl --retry 5 --retry-delay 10 --retry-connrefused http://localhost:5173

      - name: Run Lighthouse Script
        run: |
          cd lighthouse
          node lighthouse.js http://localhost:5173 lighthouse_desktop.json desktop
        
      - name: Upload Lighthouse Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: lighthouse/desktop.report.html

      - name: Mobile Lighthouse Test
        run: |
          cd lighthouse
          which bc
          chmod +x check_performance.sh
          xvfb-run --auto-servernum --server-args='-screen 0 1280x1024x24' ./check_performance.sh  http://localhost:5173 lighthouse_mobile.json mobile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Upload Lighthouse Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: lighthouse/mobile.report.html
