name: Cypress Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      FUNCTIONS_WORKER_RUNTIME: "node"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: get gh token from my-gh-app
        id: gh-app-auth
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          repositories: common-merlin-ui-kit,digital-ticketing-portal-infra

      - run: |
          git config --global url."https://oauth2:${{ steps.gh-app-auth.outputs.token }}@github.com".insteadOf ssh://git@github.com
          npm ci

      - name: Start App
        run: |
          nohup npm run start:test & # Run the app in the background
          sleep 30 # Wait for a while to ensure the app starts
          curl --retry 5 --retry-delay 10 --retry-connrefused http://localhost:5173

      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Upload Cypress screenshots
        if: always() # Ensure this step runs even if the previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        if: always() # Ensure this step runs even if the previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
